name: CI

on: [push]

jobs:
  validate-backend:
    env: 
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
      RAILS_ENV: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'

      - name: Install bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install
      
      - name: Build Postgres
        run: | 
          sudo apt-get -yqq install libpq-dev
          sudo service postgresql start

      - name: DB setup
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate
        
      - name: Run tests
        run: |
          sudo service postgresql start 
          bundle exec rspec --format documentation

      